/** Stage 1 -> 4. Takes an image, returns the id of a finished scan. */
import { NextResponse } from "next/server";
import { MAX_UPLOAD_BYTES } from "@/lib/config";
import { runPipeline } from "@/lib/pipeline/run";
import { UploadSchema } from "@/lib/schemas";
import { saveUpload } from "@/lib/uploads";
import { ensureUserKey } from "@/lib/user";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json({ error: "Send the image as multipart form data." }, { status: 400 });
  }

  const file = form.get("image");
  if (!(file instanceof File)) {
    return NextResponse.json({ error: "No image was attached." }, { status: 400 });
  }

  // Validate before reading the body into memory.
  const check = UploadSchema.safeParse({ type: file.type, size: file.size });
  if (!check.success) {
    return NextResponse.json(
      { error: check.error.issues[0]?.message ?? "That file cannot be used." },
      { status: 400 },
    );
  }

  const bytes = Buffer.from(await file.arrayBuffer());
  if (bytes.byteLength > MAX_UPLOAD_BYTES) {
    return NextResponse.json({ error: "Images must be 8 MB or smaller." }, { status: 413 });
  }

  try {
    const userKey = await ensureUserKey();
    // The scan id is generated by the database, so the image is written under a
    // temporary name first and the row records where it landed.
    const tempId = crypto.randomUUID();
    const { path } = await saveUpload(tempId, bytes, file.type);

    const result = await runPipeline({
      userKey,
      imageBase64: bytes.toString("base64"),
      mime: file.type,
      imagePath: path,
    });

    return NextResponse.json({ id: result.scanId, status: result.status }, { status: 201 });
  } catch (error) {
    console.error("[api/scan] pipeline failed:", error);
    return NextResponse.json(
      { error: "Something went wrong while analysing that image. Please try again." },
      { status: 500 },
    );
  }
}
