/**
 * Stage 1 -> 4. Takes an image, returns the id of a finished scan.
 *
 * Three guards run before anything expensive happens, in this order:
 *
 *   1. SHAPE   — type and declared size, checked before the body is read into
 *                memory, so an 80 MB upload is refused without being buffered.
 *   2. RATE    — 30 identifications per hour per client (lib/rate-limit.ts).
 *                This endpoint calls a paid API; it is the one that needs a cap.
 *   3. SIZE    — the real byte length, because a declared size is a claim.
 *
 * The image is then resized to 1600px before it is sent anywhere. See
 * lib/storage.ts for why, and for where the bytes end up.
 */
import { NextResponse } from "next/server";
import { MAX_UPLOAD_BYTES } from "@/lib/config";
import { runPipeline } from "@/lib/pipeline/run";
import { consume, prune } from "@/lib/rate-limit";
import { scanLimitPerAddressPerHour, scanLimitPerHour } from "@/lib/config";
import { UploadSchema } from "@/lib/schemas";
import { resizeForModel, store } from "@/lib/storage";
import { ensureUserKey } from "@/lib/user";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  // Two allowances, both required.
  //
  // The per-browser one is the shopper's: thirty scans is more than anyone
  // shops, and it is keyed on the cookie so that five testers on one office
  // WiFi get five allowances rather than sharing one. Keying on the address
  // alone made a pilot group throttle each other, and a collective refusal
  // reads to each of them as a fault in the app.
  //
  // The per-address one is the building's, set ten times higher, and exists so
  // that clearing a cookie is not an unlimited bypass.
  const userKey = await ensureUserKey();
  const limit = await consume(
    request.headers,
    "scan",
    scanLimitPerHour(),
    new Date(),
    `user:${userKey}`,
  );
  const addressLimit = limit.allowed
    ? await consume(request.headers, "scan-address", scanLimitPerAddressPerHour())
    : limit;
  if (!addressLimit.allowed) {
    const seconds = Math.max(1, Math.ceil((addressLimit.resetAt.getTime() - Date.now()) / 1000));
    return NextResponse.json(
      { error: "This network has made a lot of scans in the last hour. Try again later." },
      { status: 429, headers: { "Retry-After": String(seconds) } },
    );
  }
  if (!limit.allowed) {
    const seconds = Math.max(1, Math.ceil((limit.resetAt.getTime() - Date.now()) / 1000));
    return NextResponse.json(
      {
        error:
          `That is ${limit.limit} scans in an hour, which is more than anyone shops. ` +
          "Try again later.",
      },
      { status: 429, headers: { "Retry-After": String(seconds) } },
    );
  }

  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json({ error: "Send the image as multipart form data." }, { status: 400 });
  }

  const file = form.get("image");
  if (!(file instanceof File)) {
    return NextResponse.json({ error: "No image was attached." }, { status: 400 });
  }

  // Validate before reading the body into memory.
  const check = UploadSchema.safeParse({ type: file.type, size: file.size });
  if (!check.success) {
    return NextResponse.json(
      { error: check.error.issues[0]?.message ?? "That file cannot be used." },
      { status: 400 },
    );
  }

  const original = Buffer.from(await file.arrayBuffer());
  if (original.byteLength > MAX_UPLOAD_BYTES) {
    return NextResponse.json({ error: "Images must be 8 MB or smaller." }, { status: 413 });
  }

  try {
    const userKey = await ensureUserKey();

    // Resize once, then use the same bytes for the model and for storage: what
    // the shopper sees on the result page is then exactly what was analysed.
    const resized = await resizeForModel(original);

    // The scan id is generated by the database, so the image is stored under a
    // temporary id first and the row records where it landed.
    const tempId = crypto.randomUUID();
    const stored = await store(tempId, resized.bytes, resized.mime, "scans");

    const result = await runPipeline({
      userKey,
      imageBase64: resized.bytes.toString("base64"),
      mime: resized.mime,
      image: {
        imagePath: stored?.path ?? null,
        imageMime: stored?.mime ?? resized.mime,
        imageBlobUrl: stored?.blobUrl ?? null,
        imageBytes: stored?.bytes ?? null,
      },
    });

    // Opportunistic housekeeping, and deliberately not on every request: this
    // is a DELETE on the hot path of a scan, and on SQLite every write competes
    // for the same lock. One run in twenty keeps the table small without making
    // each shopper pay for it.
    if (Math.random() < 0.05) void prune();

    return NextResponse.json({ id: result.scanId, status: result.status }, { status: 201 });
  } catch (error) {
    console.error("[api/scan] pipeline failed:", error);
    return NextResponse.json(
      { error: "Something went wrong while analysing that image. Please try again." },
      { status: 500 },
    );
  }
}
