/**
 * The hand-curated product catalogue for the MVP.
 *
 * Only the *identity* of each product is fixed here: barcode, category, pack size,
 * and which UAE retailers we track it at. The nutrition and ingredient EVIDENCE is
 * not written by hand — it is fetched from Open Food Facts / Open Beauty Facts by
 * `npm run seed:fetch` (scripts/fetch-off-seed.ts) into
 * prisma/seed-data/products.json, which is committed so seeding works offline.
 *
 * THERE ARE NO PRICES HERE, AND NO STOCK FLAGS. A price enters this app in exactly
 * one way — a person records a ListingCheck, via /admin/listings or
 * `npm run listings:import`. See DECISIONS.md §36.
 *
 * `retailers` below therefore creates a WORK ITEM per retailer: "somebody should
 * check this one". It is not a claim that the product is stocked there.
 */

import type { ProductCategory } from "../../lib/schemas";

export type CatalogueEntry = {
  slug: string;
  barcode: string;
  /** "off" = Open Food Facts, "obf" = Open Beauty Facts (same API shape). */
  db: "off" | "obf";
  /** One of the eleven in lib/schemas.ts. Rules: lib/health/categories/. */
  category: ProductCategory;
  /**
   * RUBRIC.md §4 C4.0.1. Selects the per-100 basis and bounds the alternative
   * ranking. Null means "the category's default", which is a statement about what
   * we recorded, not a guess about the product.
   */
  subcategory: string | null;
  /** Pack size as sold in the UAE. Overrides whatever the open database says. */
  sizeLabel: string;
  /** Shown if the open database has no usable name. */
  fallbackName: string;
  fallbackBrand: string;
  /**
   * Which retailers we TRACK this product at. This creates a listing to be checked;
   * it is not a claim that the product is stocked, priced, or available.
   */
  retailers: string[];
};

export const CATALOGUE: CatalogueEntry[] = [
  // ---- Breakfast / cereal -------------------------------------------------
  {
    slug: "kelloggs-corn-flakes-500g",
    barcode: "3159470000120",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Corn Flakes",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kelloggs-all-bran-fibre-plus-500g",
    barcode: "3159470001424",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "All-Bran Fibre Plus",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "amazon-ae"],
  },
  {
    slug: "kelloggs-special-k-500g",
    barcode: "5050083296079",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Special K Original",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "noon", "amazon-ae"],
  },

  // ---- Dairy --------------------------------------------------------------
  {
    slug: "al-rawabi-full-cream-yogurt-400g",
    barcode: "6291030400241",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "400 g",
    fallbackName: "Full Cream Yogurt",
    fallbackBrand: "Al Rawabi",
    retailers: ["carrefour-uae", "spinneys", "kibsons", "noon"],
  },
  {
    slug: "puck-mango-yoghurt-150g",
    barcode: "5711953167577",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150 g",
    fallbackName: "Mango Yoghurt",
    fallbackBrand: "Puck",
    retailers: ["carrefour-uae", "spinneys", "noon"],
  },
  {
    slug: "puck-gouda-slices-200g",
    barcode: "5711953023095",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "Natural Gouda Cheese Slices",
    fallbackBrand: "Puck",
    retailers: ["carrefour-uae", "spinneys", "kibsons"],
  },
  {
    slug: "president-butter-250g",
    barcode: "3228020215106",
    db: "off",
    category: "fats_oils",
    subcategory: "other_fats_oils",
    sizeLabel: "250 g",
    fallbackName: "Salted Butter",
    fallbackBrand: "Président",
    retailers: ["carrefour-uae", "spinneys", "amazon-ae"],
  },

  // ---- Chilled / deli -----------------------------------------------------
  {
    slug: "hummus-classic-240g",
    barcode: "8480000808585",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "240 g",
    fallbackName: "Hummus Classic",
    fallbackBrand: "Hacendado",
    retailers: ["spinneys", "kibsons", "carrefour-uae"],
  },

  // ---- Drinks -------------------------------------------------------------
  {
    slug: "coca-cola-330ml",
    barcode: "5449000000996",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "330 ml",
    fallbackName: "Coca-Cola",
    fallbackBrand: "Coca-Cola",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae", "kibsons"],
  },
  {
    slug: "lipton-ice-tea-peach-500ml",
    barcode: "3502110005403",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500 ml",
    fallbackName: "Ice Tea Peach",
    fallbackBrand: "Lipton",
    retailers: ["carrefour-uae", "noon", "amazon-ae"],
  },
  {
    slug: "alpro-oat-no-sugars-1l",
    barcode: "5411188124689",
    db: "off",
    category: "milk",
    subcategory: "plant_milk",
    sizeLabel: "1 L",
    fallbackName: "Oat Drink No Sugars",
    fallbackBrand: "Alpro",
    retailers: ["carrefour-uae", "spinneys", "kibsons", "amazon-ae"],
  },
  {
    slug: "oatly-organic-oat-drink-1l",
    barcode: "7394376123337",
    db: "off",
    category: "milk",
    subcategory: "plant_milk",
    sizeLabel: "1 L",
    fallbackName: "Organic Oat Drink",
    fallbackBrand: "Oatly",
    retailers: ["spinneys", "kibsons", "amazon-ae"],
  },
  {
    slug: "al-rawabi-low-fat-milk-1l",
    barcode: "6291030201022",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 L",
    fallbackName: "Low Fat Milk",
    fallbackBrand: "Al Rawabi",
    retailers: ["carrefour-uae", "spinneys", "kibsons", "noon"],
  },
  {
    slug: "al-rawabi-laban-1l",
    barcode: "6291030301043",
    db: "off",
    category: "yogurt",
    subcategory: "drinking_yogurt",
    sizeLabel: "1 L",
    fallbackName: "Fresh Laban",
    fallbackBrand: "Al Rawabi",
    retailers: ["carrefour-uae", "kibsons", "noon"],
  },
  {
    slug: "al-ain-water-500ml",
    barcode: "6291100850044",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500 ml",
    fallbackName: "Bottled Drinking Water",
    fallbackBrand: "Al Ain",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae", "kibsons"],
  },

  // ---- Olive oil and fats --------------------------------------------------
  // RUBRIC §4.1. The pilot had no olive oil at all, which meant the category
  // rule with the most interesting attributes had nothing to run against.
  {
    slug: "borges-extra-virgin-olive-oil-500ml",
    barcode: "8410179100036",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "500 ml",
    fallbackName: "Extra Virgin Olive Oil",
    fallbackBrand: "Borges",
    retailers: ["carrefour-uae", "spinneys", "amazon-ae"],
  },
  {
    slug: "borges-extra-virgin-olive-oil-1l",
    barcode: "8410179101118",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "1 L",
    fallbackName: "Extra Virgin Olive Oil",
    fallbackBrand: "Borges",
    retailers: ["carrefour-uae", "spinneys", "noon"],
  },
  {
    slug: "rahma-extra-virgin-olive-oil-250ml",
    barcode: "6291003053498",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "250 ml",
    fallbackName: "Extra Virgin Olive Oil",
    fallbackBrand: "Rahma",
    retailers: ["carrefour-uae", "spinneys"],
  },

  // ---- Milk ----------------------------------------------------------------
  {
    slug: "almarai-full-fat-milk-1l",
    barcode: "6281007032261",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 L",
    fallbackName: "Full Fat Milk",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "kibsons", "noon"],
  },
  {
    slug: "nadec-milk-1l",
    barcode: "6281057010011",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 L",
    fallbackName: "Milk",
    fallbackBrand: "Nadec",
    retailers: ["carrefour-uae", "noon", "kibsons"],
  },

  // ---- Yogurt --------------------------------------------------------------
  {
    slug: "nada-greek-style-yoghurt",
    barcode: "6281018130246",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "160 g",
    fallbackName: "Greek Style Yoghurt",
    fallbackBrand: "Nada",
    retailers: ["carrefour-uae", "spinneys", "kibsons"],
  },
  {
    slug: "activia-low-fat-stirred-yoghurt",
    barcode: "6281022118209",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "180 g",
    fallbackName: "Low Fat Stirred Yoghurt",
    fallbackBrand: "Activia",
    retailers: ["carrefour-uae", "spinneys", "noon"],
  },

  // ---- Eggs ----------------------------------------------------------------
  // RUBRIC §4.4 exists to say "there is almost nothing to check on an egg", and
  // until now nothing exercised it. Open Food Facts has no UAE-tagged egg record
  // — see catalogue-report.md; these are European records for the same product
  // kind, and the checklist they produce is category behaviour, not a UAE price.
  {
    slug: "fermiers-de-loue-free-range-eggs-6",
    barcode: "3251320080617",
    db: "off",
    category: "eggs",
    subcategory: null,
    sizeLabel: "6 eggs",
    fallbackName: "Free Range Eggs",
    fallbackBrand: "Fermiers de Loué",
    retailers: ["carrefour-uae", "spinneys"],
  },
  {
    slug: "carrefour-fresh-eggs-12",
    barcode: "3270190205685",
    db: "off",
    category: "eggs",
    subcategory: null,
    sizeLabel: "12 eggs",
    fallbackName: "Fresh Eggs",
    fallbackBrand: "Carrefour",
    retailers: ["carrefour-uae"],
  },

  // ---- Bread ---------------------------------------------------------------
  {
    slug: "almarai-sliced-white-bread",
    barcode: "6281007044417",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "600 g",
    fallbackName: "Sliced White Bread",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon"],
  },
  {
    slug: "village-bakery-wholemeal-pittas",
    barcode: "4088600276267",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "6 x 60 g",
    fallbackName: "Soft Wholemeal Pittas",
    fallbackBrand: "Village Bakery",
    retailers: ["carrefour-uae", "spinneys"],
  },
  {
    slug: "tesco-wholemeal-pittas-6",
    barcode: "5000119095282",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "6 pittas",
    fallbackName: "Wholemeal Pittas",
    fallbackBrand: "Tesco",
    retailers: ["spinneys"],
  },

  // ---- Cereal and granola --------------------------------------------------
  {
    slug: "weetabix-original-430g",
    barcode: "5010029000023",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "430 g",
    fallbackName: "Weetabix Original",
    fallbackBrand: "Weetabix",
    retailers: ["carrefour-uae", "spinneys", "amazon-ae"],
  },
  {
    slug: "bjorg-granola-chocolat-350g",
    barcode: "3229820798110",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "350 g",
    fallbackName: "Granola Chocolat",
    fallbackBrand: "Bjorg",
    retailers: ["spinneys", "kibsons"],
  },

  // ---- Packaged snacks -----------------------------------------------------
  {
    slug: "pringles-original-175g",
    barcode: "5053990156009",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "175 g",
    fallbackName: "Pringles Original",
    fallbackBrand: "Pringles",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "chips-oman-15g",
    barcode: "9501100014122",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "15 g",
    fallbackName: "Chips Oman",
    fallbackBrand: "Oman Chips",
    retailers: ["carrefour-uae", "noon"],
  },
  {
    slug: "lays-classic-nature-130g",
    barcode: "3168930002987",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "130 g",
    fallbackName: "Oven Baked Classic",
    fallbackBrand: "Lay's",
    retailers: ["carrefour-uae", "noon"],
  },

  // ---- Drinks --------------------------------------------------------------
  {
    slug: "mai-dubai-water-500ml",
    barcode: "6297000611020",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500 ml",
    fallbackName: "Bottled Drinking Water",
    fallbackBrand: "Mai Dubai",
    retailers: ["carrefour-uae", "spinneys", "noon", "kibsons"],
  },
  {
    slug: "masafi-water-500ml",
    barcode: "6291001000029",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500 ml",
    fallbackName: "Bottled Drinking Water",
    fallbackBrand: "Masafi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

  // ---- Cosmetics ----------------------------------------------------------
  {
    slug: "nivea-sun-protect-bronze-spf20-200ml",
    barcode: "4005900462060",
    db: "obf",
    category: "cosmetic",
    subcategory: null,
    sizeLabel: "200 ml",
    fallbackName: "Sun Protect & Bronze SPF 20 Spray",
    fallbackBrand: "Nivea Sun",
    retailers: ["carrefour-uae", "noon", "amazon-ae"],
  },
  {
    slug: "garnier-honey-treasures-shampoo-300ml",
    barcode: "3600542462228",
    db: "obf",
    category: "cosmetic",
    subcategory: null,
    sizeLabel: "300 ml",
    fallbackName: "Honey Treasures Shampoo",
    fallbackBrand: "Garnier",
    retailers: ["carrefour-uae", "noon", "amazon-ae", "spinneys"],
  },

  // ---- Olive oil ----------------------------------------------------------
  // Added so the olive-oil comparison has something to compare. Every barcode
  // here was checked against Open Food Facts with countries_tags=United Arab
  // Emirates before it was written down; none is typed from memory.
  {
    slug: "organic-larder-olive-oil-750ml",
    barcode: "6291104283510",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "750 ml",
    fallbackName: "Organic Olive Oil",
    fallbackBrand: "Organic Larder",
    retailers: ["carrefour-uae", "spinneys", "kibsons"],
  },
  {
    slug: "al-wazir-virgin-olive-oil-175ml",
    barcode: "8428483200151",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "175 ml",
    fallbackName: "Virgin Olive Oil",
    fallbackBrand: "Al Wazir",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "taverna-extra-virgin-olive-oil-1l",
    barcode: "1026010010210",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "1 L",
    fallbackName: "Extra Virgin Olive Oil",
    fallbackBrand: "Taverna",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

  // ---- Rice ---------------------------------------------------------------
  {
    slug: "organic-larder-basmati-rice-1kg",
    barcode: "6291104283725",
    db: "off",
    category: "food",
    subcategory: "rice",
    sizeLabel: "1 kg",
    fallbackName: "Organic Basmati Rice",
    fallbackBrand: "Organic Larder",
    retailers: ["carrefour-uae", "spinneys", "kibsons"],
  },
  {
    slug: "rozana-indian-basmati-rice-5kg",
    barcode: "8901537075764",
    db: "off",
    category: "food",
    subcategory: "rice",
    sizeLabel: "5 kg",
    fallbackName: "Indian Basmati Rice",
    fallbackBrand: "Rozana",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "dawat-basmati-rice-1kg",
    barcode: "8901537075832",
    db: "off",
    category: "food",
    subcategory: "rice",
    sizeLabel: "1 kg",
    fallbackName: "Basmati Rice",
    fallbackBrand: "Dawat",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

  // ---- Pasta --------------------------------------------------------------
  {
    slug: "emirates-macaroni-penne-400g",
    barcode: "6291047020876",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "400 g",
    fallbackName: "Penne",
    fallbackBrand: "Emirates Macaroni",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "barilla-casarecce-500g",
    barcode: "8076809519960",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "500 g",
    fallbackName: "Casarecce n. 87",
    fallbackBrand: "Barilla",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "barilla-whole-wheat-penne-500g",
    barcode: "8076809529433",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "500 g",
    fallbackName: "Whole Wheat Penne Rigate",
    fallbackBrand: "Barilla",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

  // ---- Canned food --------------------------------------------------------
  {
    slug: "california-garden-fava-beans-260g",
    barcode: "0032894010902",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "260 g",
    fallbackName: "Fava Beans Lebanese Recipe",
    fallbackBrand: "California Garden",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "farm-fresh-sweet-corn-425g",
    barcode: "6291079225775",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "425 g",
    fallbackName: "Whole Kernel Sweet Corn",
    fallbackBrand: "Farm Fresh",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "alalali-tuna-170g",
    barcode: "0617950143734",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "170 g",
    fallbackName: "Tuna",
    fallbackBrand: "Alalali",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

  // ---- Sauces -------------------------------------------------------------
  {
    slug: "noor-ketchup-less-sugar-410g",
    barcode: "6291003628931",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "410 g",
    fallbackName: "Tomato Ketchup, 50% less sugar and salt",
    fallbackBrand: "Noor",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "heinz-tomato-ketchup-295g",
    barcode: "6221033001015",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "295 g",
    fallbackName: "Tomato Ketchup",
    fallbackBrand: "Heinz",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "sacla-cherry-tomato-sauce-350g",
    barcode: "8001060008403",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "350 g",
    fallbackName: "Whole Cherry Tomato Sauce with Chilli",
    fallbackBrand: "Saclà",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },


  // ---- UAE pilot expansion --------------------------------------------------
  // Harvested by scripts/discover-uae.ts from Open Food Facts records tagged as
  // sold in the United Arab Emirates. Every entry survived four filters: a real
  // UAE tag, a real name/brand/GTIN, a stated pack size, and enough nutrition to
  // actually run the category's checks. Products that would only ever return
  // COULD NOT VERIFY were dropped rather than padded in.
  {
    slug: "zahmed-aceite-de-oliva-virgen-extra",
    barcode: "8426563547981",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "1 l",
    fallbackName: "Aceite de oliva virgen extra",
    fallbackBrand: "Zahmed",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "carluccio-s-aceite-de-oliva-virgen-extra",
    barcode: "5050283406537",
    db: "off",
    category: "fats_oils",
    subcategory: "olive_oil",
    sizeLabel: "1",
    fallbackName: "Aceite de oliva virgen extra",
    fallbackBrand: "Carluccio's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "pure-harvest-organic-almond-unsweetened",
    barcode: "9312231001215",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 litre",
    fallbackName: "Organic Almond Unsweetened",
    fallbackBrand: "Pure Harvest",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-",
    barcode: "6281007120401",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "2L",
    fallbackName: "المراعي حليب",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-almarai-lacto-free-milk-full-fat",
    barcode: "6281007033565",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1L",
    fallbackName: "Almarai lacto free milk full fat",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "-rainbow-milk-w-cardamon",
    barcode: "8716200675048",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "160g",
    fallbackName: "Rainbow Milk w/ Cardamon",
    fallbackBrand: "ابو قوس",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai--3110",
    barcode: "6281007073110",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "400ml",
    fallbackName: "حليب بروتين بالشوكلاته",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai--0501",
    barcode: "6281007110501",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "2l",
    fallbackName: "لبن المراعي قليل الدسم",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "cacaolat-cacaolat-0",
    barcode: "8412700120100",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "200 ml",
    fallbackName: "Cacaolat 0%",
    fallbackBrand: "Cacaolat",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai--2544",
    barcode: "6281007032544",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "360 ml",
    fallbackName: "المراعي حليب بالفراوله",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-almarai-vanilla-flavored-milk",
    barcode: "6281007038959",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "150 ml",
    fallbackName: "Almarai vanilla flavored milk",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "-protein-milk-34g-strawberry-and-banana-fat-free-400ml",
    barcode: "6281007062732",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "400مل",
    fallbackName: "Protein Milk 34g Strawberry and Banana Fat Free 400ml",
    fallbackBrand: "المراعي",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lacnor-milk",
    barcode: "6291016011027",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 l",
    fallbackName: "Milk",
    fallbackBrand: "Lacnor",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "-",
    barcode: "4610046800012",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "370g",
    fallbackName: "молоко цельное сгущеное с сахаром",
    fallbackBrand: "Карламанский молочный комбинат",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-evaporated-milk",
    barcode: "6281007035187",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "170 g",
    fallbackName: "Evaporated milk",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "safa-strawberry-milk",
    barcode: "6291044100175",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "200g",
    fallbackName: "Strawberry Milk",
    fallbackBrand: "Safa",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "koita-organic-skim-milk",
    barcode: "0863769000229",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1L",
    fallbackName: "organic skim milk",
    fallbackBrand: "koita",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "auga-organic-milk",
    barcode: "4771085204855",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 l",
    fallbackName: "Organic Milk",
    fallbackBrand: "Auga",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "galaxy-galaxy",
    barcode: "5060402903830",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "350",
    fallbackName: "Galaxy",
    fallbackBrand: "Galaxy",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "auga-organic-milk-4862",
    barcode: "4771085204862",
    db: "off",
    category: "milk",
    subcategory: "dairy_milk",
    sizeLabel: "1 l",
    fallbackName: "Organic Milk",
    fallbackBrand: "Auga",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai--0655",
    barcode: "6281007040655",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "170 g",
    fallbackName: "زبادي المراعي",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "bauer-mango-yogurt",
    barcode: "4002334117757",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150 g",
    fallbackName: "Mango Yogurt",
    fallbackBrand: "Bauer",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai--6466",
    barcode: "6281007046466",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150 g",
    fallbackName: "المراعي زبادي بالفراوله",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "laban-up-safa-laban-up-200-ml",
    barcode: "6291044110358",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "200ml",
    fallbackName: "Safa Laban Up 200 ml",
    fallbackBrand: "Laban Up",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "activia-",
    barcode: "6281022118063",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "180 mL",
    fallbackName: "اكتيفيا لبن قليل الدسم",
    fallbackBrand: "Activia",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "elle-vire-elle-vire-desserts-lactes-fruits-peche",
    barcode: "3451790019739",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "4 x 125 g",
    fallbackName: "Elle & vire desserts lactes fruits peche",
    fallbackBrand: "Elle & Vire",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-ain-farms-yoghurt",
    barcode: "6291056060504",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "170 grams",
    fallbackName: "Yoghurt",
    fallbackBrand: "Al Ain Farms",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "safa-laban-up-sweetened-laban-drink",
    barcode: "6291044444910",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "200 ml",
    fallbackName: "Laban up - sweetened laban drink",
    fallbackBrand: "Safa",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "olympus-yogurt-greco-alla-pesca",
    barcode: "5202178001901",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150 g",
    fallbackName: "Yogurt greco alla pesca",
    fallbackBrand: "Olympus",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "logo-yogurt",
    barcode: "0629025442352",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "6 x 100 g",
    fallbackName: "Yogurt",
    fallbackBrand: "Logo",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "rachel-s-greek-style-natural",
    barcode: "5021638100820",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "500 g",
    fallbackName: "Greek Style Natural",
    fallbackBrand: "Rachel's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "abu-dhabi-laban-up",
    barcode: "6291074292352",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "200ml",
    fallbackName: "Laban up",
    fallbackBrand: "Abu Dhabi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "marmum-fresh-greek-yogurt-strawberry",
    barcode: "6291031000709",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150g 1x",
    fallbackName: "Fresh Greek Yogurt - Strawberry",
    fallbackBrand: "Marmum",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nada-greek-drinking-yoghurt-passion-fruit-with-chia-seeds-w",
    barcode: "0207618275541",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "330 ml",
    fallbackName: "Greek Drinking Yoghurt passion fruit with chia seeds with mixed fruit",
    fallbackBrand: "Nada",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "arla-foods-arla-protein-strawberry",
    barcode: "7217101111112",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150g",
    fallbackName: "Arla protein strawberry",
    fallbackBrand: "Arla Foods",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "yoplait-fresh-and-creamy",
    barcode: "6291100852222",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "120 g",
    fallbackName: "fresh and creamy",
    fallbackBrand: "Yoplait",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nada-",
    barcode: "6281018146988",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "160 g",
    fallbackName: "ندى زبادي يوناني قليل الدسم",
    fallbackBrand: "nada",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "fage-total-fat-free-greek-recipe-strained-yoghurt",
    barcode: "5201054017814",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "150 g",
    fallbackName: "Total Fat Free Greek Recipe Strained Yoghurt",
    fallbackBrand: "FAGE",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "i-go-i-go-flavoured-pureed-yogurt",
    barcode: "0629025404565",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "100g",
    fallbackName: "Iögo flavoured pureed yogurt",
    fallbackBrand: "iögo",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-a-n-farms-greek-yoghurt-drink",
    barcode: "6291056002467",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "280 ml",
    fallbackName: "greek yoghurt drink",
    fallbackBrand: "Al Aïn farms",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "hayatna-hayatna-greek-yogurt",
    barcode: "6297001135754",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "360g",
    fallbackName: "Hayatna Greek Yogurt",
    fallbackBrand: "hayatna",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "spinneysfood-greek-style-vanilla-yoghurt",
    barcode: "29590438",
    db: "off",
    category: "yogurt",
    subcategory: "spoonable_yogurt",
    sizeLabel: "450 g",
    fallbackName: "Greek-Style Vanilla Yoghurt",
    fallbackBrand: "Spinneysfood",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "organic-larder-large-brown-organic-eggs",
    barcode: "6291104283077",
    db: "off",
    category: "eggs",
    subcategory: null,
    sizeLabel: "10 pcs",
    fallbackName: "Large brown organic eggs",
    fallbackBrand: "Organic Larder",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-corn-flakes",
    barcode: "5053827185806",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375",
    fallbackName: "Corn Flakes",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-crunchy-nut",
    barcode: "5000127049307",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Crunchy Nut",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-kelloggs-coco-pops-original",
    barcode: "5059319024882",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "330 g",
    fallbackName: "Kelloggs coco pops original",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-kelloggs-corn-flakes-the-original",
    barcode: "4003994111901",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500g",
    fallbackName: "Kelloggs corn flakes the original",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nestl-go-up",
    barcode: "7613036438100",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "40g",
    fallbackName: "Go up",
    fallbackBrand: "Nestlé",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "organix-organix-banana-peach-apple-muesli",
    barcode: "5024121217319",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "Organix Banana, Peach & Apple Muesli",
    fallbackBrand: "organix",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "orgran-orgran-multigrain-o-s-with-quinoa",
    barcode: "0720516021916",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "300g",
    fallbackName: "Orgran Multigrain O's With Quinoa",
    fallbackBrand: "Orgran",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "amisa-honey-puffs",
    barcode: "5032722307889",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "Honey puffs",
    fallbackBrand: "Amisa",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-froot-loops",
    barcode: "5059319034102",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375gm",
    fallbackName: "Froot loops",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-miel-pops",
    barcode: "5050083597367",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375g",
    fallbackName: "miel pops",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-crunchy-muesli-with-fruit",
    barcode: "5053827144056",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Crunchy Muesli With Fruit",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nestl-lion-caramel-and-chocolate",
    barcode: "7613034215406",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "480g",
    fallbackName: "Lion Caramel and Chocolate",
    fallbackBrand: "Nestlé",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "weetabix-weetabix-original-100-wholegrain",
    barcode: "2020000013495",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "430 g",
    fallbackName: "Weetabix original 100% Wholegrain",
    fallbackBrand: "Weetabix",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nestl-nesquik",
    barcode: "7613037057683",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "450g",
    fallbackName: "Nesquik",
    fallbackBrand: "Nestlé",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "munchbox-granola",
    barcode: "0759170105144",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Granola",
    fallbackBrand: "Munchbox",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "neskers-corn-flakes",
    barcode: "9100005918902",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375 g",
    fallbackName: "Corn flakes",
    fallbackBrand: "Neskers",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "quaker-quaker-oat-crisp-cereal-375-g",
    barcode: "2000000039883",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375",
    fallbackName: "Quaker Oat Crisp Cereal 375 g",
    fallbackBrand: "Quaker",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "spinneys-food-cornflakes",
    barcode: "29574322",
    db: "off",
    category: "cereal",
    subcategory: null,
    sizeLabel: "375g",
    fallbackName: "Cornflakes",
    fallbackBrand: "Spinneys Food",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "scotti-risotto-tartufo",
    barcode: "3048860257131",
    db: "off",
    category: "food",
    subcategory: "rice",
    sizeLabel: "210 g",
    fallbackName: "Risotto Tartufo",
    fallbackBrand: "Scotti",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "indomie-indomie-instant-noodles-baladi-chicken-flavor",
    barcode: "5285000390640",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "70 g",
    fallbackName: "Indomie instant noodles baladi chicken flavor",
    fallbackBrand: "indomie",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "maggi-instant-noodles-soup-with-curry-flavour",
    barcode: "9556001302793",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "79g",
    fallbackName: "Instant Noodles Soup with Curry Flavour",
    fallbackBrand: "Maggi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "maggi-noodles-soup-with-chicken-flavour",
    barcode: "9556001302748",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "5x77g",
    fallbackName: "Noodles soup with chicken flavour",
    fallbackBrand: "Maggi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "bare-naked-foods-spaghetti",
    barcode: "0634158766404",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "250 g",
    fallbackName: "Spaghetti",
    fallbackBrand: "Bare Naked Foods",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "spinners-whole-wheat-spaghetti",
    barcode: "22245908",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "500g",
    fallbackName: "Whole wheat spaghetti",
    fallbackBrand: "Spinners",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "scoiattolo-ravioli-pomodoro-mozzarella",
    barcode: "8006669012172",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "250 g",
    fallbackName: "Ravioli pomodoro mozzarella",
    fallbackBrand: "Scoiattolo",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lucky-me-pancit-canton-sweet-spicy",
    barcode: "4807770272578",
    db: "off",
    category: "food",
    subcategory: "pasta",
    sizeLabel: "360g",
    fallbackName: "Pancit canton sweet & spicy",
    fallbackBrand: "Lucky Me!",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "flying-goose-brand-sweet-chili-sauce",
    barcode: "8853662056326",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "200 ml",
    fallbackName: "Sweet chili sauce",
    fallbackBrand: "flying goose brand",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "heinz-heinz-sar-msakl-garlic",
    barcode: "8410066128624",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "230 g",
    fallbackName: "Heinz Sarımsaklı Garlic",
    fallbackBrand: "Heinz",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nando-s-peri-peri-sauce-medium",
    barcode: "6003770000168",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "​​250g",
    fallbackName: "PERi-PERi Sauce Medium",
    fallbackBrand: "Nando's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "ama-barbacue-sauce",
    barcode: "6299200002899",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "350ml",
    fallbackName: "barbacue sauce",
    fallbackBrand: "ama",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "biona-mustard-wholegrain",
    barcode: "5032722304932",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "200 g",
    fallbackName: "Mustard Wholegrain",
    fallbackBrand: "Biona",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "heinz-thousand-island-dressing",
    barcode: "6290090014993",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "400 ml",
    fallbackName: "Thousand Island Dressing",
    fallbackBrand: "Heinz",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "heing-chili-mayonnaise",
    barcode: "6290090033185",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "400 ml",
    fallbackName: "Chili mayonnaise",
    fallbackBrand: "Heing",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lady-s-choice-lady-s-choice-bacon-spread",
    barcode: "4808680022314",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "220 mL",
    fallbackName: "Lady's Choice Bacon Spread",
    fallbackBrand: "Lady's Choice",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "goody-tomato-ketchup",
    barcode: "6281014303644",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "980 grammes",
    fallbackName: "Tomato Ketchup",
    fallbackBrand: "Goody",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "sacl-sacla-pesto-classic-basil",
    barcode: "8001060013506",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "290 g",
    fallbackName: "Sacla Pesto classic basil",
    fallbackBrand: "Saclà",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "spinneysfood-peri-peri-hummus",
    barcode: "29570799",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "200 g",
    fallbackName: "Peri peri hummus",
    fallbackBrand: "SpinneysFood",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "american-garden-garlic-herb-pasta-sauce",
    barcode: "0717273508347",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "397g",
    fallbackName: "Garlic Herb Pasta Sauce",
    fallbackBrand: "American Garden",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "sacl-wild-garlic-pesto",
    barcode: "8001060013919",
    db: "off",
    category: "food",
    subcategory: "sauce",
    sizeLabel: "190g",
    fallbackName: "Wild Garlic Pesto",
    fallbackBrand: "Saclà",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "evian-evian-mineral-water",
    barcode: "3068320109596",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "50 cl",
    fallbackName: "Evian Mineral Water",
    fallbackBrand: "Evian",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "aquafina-water",
    barcode: "0012000014338",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500ml",
    fallbackName: "water",
    fallbackBrand: "Aquafina",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "arwa-",
    barcode: "54493704",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "1",
    fallbackName: "أروى",
    fallbackBrand: "Arwa",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "oasis-oasis-bottled-drinking-water",
    barcode: "6291021210712",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500 ml",
    fallbackName: "Oasis Bottled Drinking Water",
    fallbackBrand: "Oasis",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mai-dubai-water",
    barcode: "6297000611006",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "1.5 l",
    fallbackName: "Water",
    fallbackBrand: "Mai dubai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-ain-al-ain-pure-natural-bottled-water",
    barcode: "6291100850068",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "1,5 l",
    fallbackName: "Al ain pure natural bottled water",
    fallbackBrand: "Al ain",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mai-dubai-mai-dubai",
    barcode: "6297000611075",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "330ml",
    fallbackName: "Mai Dubai",
    fallbackBrand: "Mai Dubai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "masafi-masafi-zero",
    barcode: "6291001014729",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500ml",
    fallbackName: "Masafi zero",
    fallbackBrand: "Masafi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-ain-ph-7-3-water",
    barcode: "6291101036096",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500ml",
    fallbackName: "pH 7.3 Water",
    fallbackBrand: "Al ain",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-ain-zero-bottled-drinking-water",
    barcode: "6291105811231",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500ml",
    fallbackName: "Zero bottled drinking water",
    fallbackBrand: "Al ain",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "g-v-ltd-cleopatra-gold-24k-water",
    barcode: "6290360088242",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "0.33L e",
    fallbackName: "Cleopatra Gold 24K Water",
    fallbackBrand: "G&V Ltd.",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "masafi-pure-bottled-drinking-water",
    barcode: "11155553",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "500ml",
    fallbackName: "Pure bottled drinking water",
    fallbackBrand: "Masafi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "oxylife-water-oxygen-water-oxylife-water-with-high-and-stabl",
    barcode: "8594174360067",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "250 ml",
    fallbackName: "Oxygen water Oxylife water with HIGH and stable oxygen nano bubbles. kyslíková voda",
    fallbackBrand: "Oxylife Water",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "ok-snacks-a-s-kettle-cooked-chips",
    barcode: "5701397301330",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "150g",
    fallbackName: "Kettle Cooked Chips",
    fallbackBrand: "OK snacks a/s",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "doritos-doritos-nacho-cheese",
    barcode: "6281036564108",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "48g",
    fallbackName: "Doritos Nacho Cheese",
    fallbackBrand: "Doritos",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "al-jufair-food-oman-chips-madium",
    barcode: "9501100017413",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100g",
    fallbackName: "Oman Chips Madium",
    fallbackBrand: "Al jufair food",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kettle-cooked-kettle-cooked-chips-sweet-bbq",
    barcode: "5701397326616",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "150g",
    fallbackName: "Kettle Cooked Chips Sweet BBQ",
    fallbackBrand: "Kettle cooked",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "miaow-miaow-60",
    barcode: "9556345008573",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "60 g",
    fallbackName: "مياو مياو مقرمشات بالروبيان 60 جرام",
    fallbackBrand: "Miaow Miaow",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "ybc-",
    barcode: "4903015560223",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "65g",
    fallbackName: "エアリアル 濃厚チェダーチーズ",
    fallbackBrand: "YBC",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "brb-rice-popped-chips-classic-salted",
    barcode: "8906117090762",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "48 g",
    fallbackName: "Rice Popped Chips - Classic Salted",
    fallbackBrand: "BRB",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mr-krisps-salad-chips",
    barcode: "6291028127204",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "1 qty, 55g",
    fallbackName: "Salad Chips",
    fallbackBrand: "Mr.Krisps",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "old-el-paso-tortilla-chips",
    barcode: "8410076482730",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "185 g",
    fallbackName: "Tortilla chips",
    fallbackBrand: "Old El Paso",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "old-el-paso-nachips",
    barcode: "8410076482723",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "185 g",
    fallbackName: "Nachips",
    fallbackBrand: "Old El Paso",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "spinneysfood-sour-cream-and-onion-crisps",
    barcode: "29634477",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "40g",
    fallbackName: "Sour cream and onion crisps",
    fallbackBrand: "SpinneysFOOD",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "laperva-protein-chips",
    barcode: "5412860335430",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "55g",
    fallbackName: "Protein chips",
    fallbackBrand: "LAPERVA",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "soler-s-pita-chips-avec-thym",
    barcode: "5287001078152",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "150 g",
    fallbackName: "Pita Chips Avec Thym",
    fallbackBrand: "SOLER'S",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kurkure-red-chili-chatka",
    barcode: "6281036024053",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "16 g",
    fallbackName: "Red Chili Chatka",
    fallbackBrand: "Kurkure",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "alkabbos-mr-chips",
    barcode: "6291104236585",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "12g",
    fallbackName: "Mr.chips",
    fallbackBrand: "Alkabbos",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "anand-jolliz-namkeen-harissa-chilli-potato-chips",
    barcode: "8906069612272",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "135g",
    fallbackName: "Jolliz Namkeen Harissa Chilli Potato Chips",
    fallbackBrand: "Anand",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "anand-jolliz-namkeen-cream-onion-chips",
    barcode: "8906069612371",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "135g",
    fallbackName: "Jolliz Namkeen Cream Onion Chips",
    fallbackBrand: "Anand",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "arnott-s-tim-tam",
    barcode: "9310072000282",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "200g",
    fallbackName: "Tim Tam",
    fallbackBrand: "Arnott's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mcvities-mcvities-digestive-dark-chocolate",
    barcode: "5000396014877",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "McVities Digestive Dark Chocolate",
    fallbackBrand: "McVities",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mcvitie-s-digestives-milk-chocolate",
    barcode: "5000396014822",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "200g",
    fallbackName: "Digestives Milk Chocolate",
    fallbackBrand: "McVitie's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "oreo-oreo-cookies",
    barcode: "7622201765286",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "36.8g",
    fallbackName: "Oreo Cookies",
    fallbackBrand: "Oreo",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "ritz-ritz",
    barcode: "7622201747152",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "39.6",
    fallbackName: "RITZ",
    fallbackBrand: "Ritz",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "roshen-lovita-blondie-brownie-lemon",
    barcode: "4823077646287",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "152",
    fallbackName: "Lovita Blondie Brownie Lemon",
    fallbackBrand: "Roshen",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "rhythm-108-double-chocolate-hazelnut-biscuits",
    barcode: "7640155340502",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "135g",
    fallbackName: "Double Chocolate Hazelnut Biscuits",
    fallbackBrand: "Rhythm 108",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "britannia-digestive-sugar-free-biscuits",
    barcode: "6291007902181",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "200g",
    fallbackName: "Digestive Sugar Free Biscuits",
    fallbackBrand: "Britannia",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "belvita-biscuit-bran",
    barcode: "7622201746667",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "56 g",
    fallbackName: "Biscuit Bran",
    fallbackBrand: "Belvita",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "rhythm-108-vegan-coconut-crunch",
    barcode: "7640155340533",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "135 g",
    fallbackName: "Vegan coconut crunch",
    fallbackBrand: "Rhythm 108",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lker-petit-beurre-biscuits",
    barcode: "8690504011408",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "450 g",
    fallbackName: "petit beurre biscuits",
    fallbackBrand: "Ülker",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lotus-lotus-caramelised-biscuits-156g",
    barcode: "5410126116168",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "156 g",
    fallbackName: "Lotus (Caramelised Biscuits, 156G)",
    fallbackBrand: "Lotus",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mcvitie-s-mcvities-digestive25-light-biscuits",
    barcode: "5000396032925",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Mcvities Digestive25% Light Biscuits",
    fallbackBrand: "McVitie's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "pran-pran-potato-biscuits",
    barcode: "0840205713035",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "50gm",
    fallbackName: "Pran Potato biscuits",
    fallbackBrand: "Pran",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "tiffany-digestive-natural-wheat-biscuit",
    barcode: "6291003000157",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "2packs 400g",
    fallbackName: "Natural wheat biscuit",
    fallbackBrand: "Tiffany Digestive",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "pocky-pocky-cacao-60",
    barcode: "4901005512696",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "54 g",
    fallbackName: "Pocky Cacao 60%",
    fallbackBrand: "Pocky",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "tiffany-delights-bourbon-creams",
    barcode: "6291003000577",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "200g",
    fallbackName: "Delights Bourbon Creams",
    fallbackBrand: "Tiffany",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "tiffany-happy-break",
    barcode: "6291003081934",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "16 g",
    fallbackName: "Happy Break",
    fallbackBrand: "Tiffany",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mcvitie-s-digestive-nibbles",
    barcode: "8690504037743",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "110g",
    fallbackName: "Digestive nibbles المحجر",
    fallbackBrand: "McVitie's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "tiffany-tiffany-delight-choco-chip-cookie-s",
    barcode: "6291003010347",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "90 g",
    fallbackName: "Tiffany delight Choco Chip Cookie's",
    fallbackBrand: "Tiffany",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "igloo-cookies-creem",
    barcode: "6291003602931",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "120ml",
    fallbackName: "Cookies & creem",
    fallbackBrand: "Igloo",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-zen-mini-cookies",
    barcode: "6297001558065",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "120 g",
    fallbackName: "Zen Mini Cookies",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "tiffany-everyday-nice-sugar-sprinkled-coconut-biscuits",
    barcode: "6291003002205",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "50 g",
    fallbackName: "Everyday Nice Sugar sprinkled coconut biscuits",
    fallbackBrand: "Tiffany",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nhf-gluten-free-chocolate-butter-cookies",
    barcode: "9555432807747",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "30g/packet *6",
    fallbackName: "Gluten free Chocolate butter cookies",
    fallbackBrand: "NHF",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "riddle-peanut-butter-wafer-coated-in-milk-chocolate",
    barcode: "5203225003985",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "45 gr",
    fallbackName: "peanut butter wafer coated in milk chocolate",
    fallbackBrand: "Riddle",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "manji-high-fibre-biscuits",
    barcode: "6161101251761",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100g e",
    fallbackName: "High Fibre Biscuits",
    fallbackBrand: "Manji",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "koala-picks-peanut-butter-cookies",
    barcode: "0793618133535",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "8 cookies - 160g",
    fallbackName: "Peanut Butter Cookies",
    fallbackBrand: "Koala Picks",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "waitrose-sicilian-lemon-white-chocolate-all-butter-cookies",
    barcode: "5063210013968",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "150g",
    fallbackName: "Sicilian Lemon & White Chocolate All Butter Cookies",
    fallbackBrand: "Waitrose",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kellogg-s-frosted-strawberry-toaster-pastries-strawberry",
    barcode: "0038000317101",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "416 g",
    fallbackName: "Frosted strawberry toaster pastries, strawberry",
    fallbackBrand: "Kellogg's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "garden-savoury-crackers",
    barcode: "0089782000491",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "150g (5,3oz)",
    fallbackName: "Savoury crackers",
    fallbackBrand: "Garden",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "nestl-fitness-biscuits",
    barcode: "6221007031703",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "12 x 30 g",
    fallbackName: "Fitness biscuits",
    fallbackBrand: "Nestlé",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "britannia-digestive-original-biscuits",
    barcode: "6291007910537",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "400 g",
    fallbackName: "Digestive original biscuits",
    fallbackBrand: "Britannia",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "waitrose-fig-plum-and-cranberry-wheat-biscuit",
    barcode: "5000169389300",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "130",
    fallbackName: "Fig plum and cranberry wheat biscuit",
    fallbackBrand: "Waitrose",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "britannia-good-day-cashew-cookies",
    barcode: "6291007901047",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "81 g",
    fallbackName: "Good day cashew cookies",
    fallbackBrand: "Britannia",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "sunfeast-mom-s-magic",
    barcode: "8901725117337",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "750",
    fallbackName: "MOM'S MAGIC",
    fallbackBrand: "Sunfeast",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-moketo",
    barcode: "6297001558157",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "72 g",
    fallbackName: "MoKeto",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-smart-mini-cookies",
    barcode: "6297001558058",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "120 g",
    fallbackName: "Smart Mini Cookies",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-love-mini-cookies",
    barcode: "6297001558072",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "120 g",
    fallbackName: "Love Mini Cookies",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "m-y-san-graham-crackers",
    barcode: "0750515021150",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "800 g",
    fallbackName: "Graham Crackers",
    fallbackBrand: "M.Y. San",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "natur-s-breakfast-biscuits-chocolate-hazelnut-and-honey",
    barcode: "6299200045889",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "300 g",
    fallbackName: "Breakfast Biscuits Chocolate, Hazelnut and Honey",
    fallbackBrand: "Natur's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "puck-puck-spreadable-processed-cream-cheese-analogue-500g",
    barcode: "5760466738040",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "500 g",
    fallbackName: "Puck spreadable processed cream cheese analogue 500g",
    fallbackBrand: "Puck",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "philadelphia-philadelphia-original",
    barcode: "7622210624840",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "180g",
    fallbackName: "Philadelphia Original",
    fallbackBrand: "Philadelphia",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "arla-puck-jars-white",
    barcode: "5760466738095",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "240gr",
    fallbackName: "Puck Jars White",
    fallbackBrand: "Arla",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "president-edam",
    barcode: "8718444725206",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "150 g",
    fallbackName: "Edam",
    fallbackBrand: "President",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-cream-cheese-12",
    barcode: "6281007023962",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "216g",
    fallbackName: "Cream cheese*12",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "puck-cheese-sticks",
    barcode: "5711953000782",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "108g",
    fallbackName: "Cheese sticks",
    fallbackBrand: "Puck",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "soignon-goat-s-cheese-honey",
    barcode: "3523230039369",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "125 g",
    fallbackName: "Goat's cheese honey",
    fallbackBrand: "Soignon",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "puck-processed-cheese-triangles",
    barcode: "6281048106990",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "24 portions",
    fallbackName: "Processed Cheese Triangles",
    fallbackBrand: "PUCK",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "bel-abu-walad-regal-picon",
    barcode: "3251350161003",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "16 portion",
    fallbackName: "Abu walad Regal picon",
    fallbackBrand: "Bel",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kiri-kiri-spread-cream-cheese",
    barcode: "3073781010725",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "200g",
    fallbackName: "Kiri spread cream cheese",
    fallbackBrand: "Kiri",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "dodoni-feta-cheese-p-d-o-lactose-free",
    barcode: "5201168815399",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "150 g",
    fallbackName: "Feta cheese (P.D.O.) lactose free",
    fallbackBrand: "Dodoni",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "president-cr-ation-cheese",
    barcode: "5941192110335",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "1 kg,",
    fallbackName: "Création cheese",
    fallbackBrand: "President",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "puck-puck-jars-white",
    barcode: "5711953157981",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "500g",
    fallbackName: "Puck Jars White",
    fallbackBrand: "PUCK",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "livecross-farm-organic-mature-cheddar",
    barcode: "5027632000418",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "Organic Mature Cheddar",
    fallbackBrand: "Livecross Farm",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kraft-cheddar-cheese",
    barcode: "0840370901381",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "12 oz",
    fallbackName: "Cheddar cheese",
    fallbackBrand: "Kraft",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "frico-gouda-light",
    barcode: "8710912505075",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "150 g",
    fallbackName: "Gouda light",
    fallbackBrand: "Frico",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-ptotein-bites-parmesan-and-black-pepper",
    barcode: "6297001558140",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "120 g",
    fallbackName: "Ptotein Bites - Parmesan and Black Pepper",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "quattrocolli-grana-padano",
    barcode: "8016129000854",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "150 g",
    fallbackName: "Grana padano",
    fallbackBrand: "Quattrocolli",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "president-quot-quot-9",
    barcode: "4823065731704",
    db: "off",
    category: "food",
    subcategory: null,
    sizeLabel: "300 g",
    fallbackName: "Сир кисломолочний \"Сирна Традиція\", 9% жиру",
    fallbackBrand: "President",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "sun-top-sun-top-orange",
    barcode: "6281012033185",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "250ml",
    fallbackName: "Sun top orange",
    fallbackBrand: "Sun top",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-orange-juice-200",
    barcode: "6281007055284",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "200ml",
    fallbackName: "Orange Juice 200",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "almarai-orange-carrot-juice",
    barcode: "6281007806831",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "300ml",
    fallbackName: "orange & carrot juice",
    fallbackBrand: "Almarai",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "carrefour-apple-orange-juice",
    barcode: "6291108225424",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "200ml",
    fallbackName: "Apple orange juice",
    fallbackBrand: "Carrefour",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "coca-cola-services-sa-nv-coca-cola-zero-az-car",
    barcode: "5449000131805",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "330ml",
    fallbackName: "Coca-Cola Zero Azúcar",
    fallbackBrand: "COCA-COLA SERVICES SA/NV",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "schweppes-slimline-lemonade",
    barcode: "5000193730574",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "2 l",
    fallbackName: "Slimline Lemonade",
    fallbackBrand: "Schweppes",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "up-unfiltered-ginger-brew-2yrs-prod",
    barcode: "6291109600381",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "330ml",
    fallbackName: "Unfiltered Ginger Brew 2yrs prod",
    fallbackBrand: "Up",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "cola-pepsi",
    barcode: "0012000800085",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "400",
    fallbackName: "Pepsi",
    fallbackBrand: "Cola",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "schweppes-ginger-ale",
    barcode: "5449000060303",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "300 ml",
    fallbackName: "Ginger ale",
    fallbackBrand: "Schweppes",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "coca-cola-cocacola-original-taste",
    barcode: "5449000043382",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "355 ml",
    fallbackName: "Cocacola original taste",
    fallbackBrand: "Coca Cola",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "waitrose-lemonade",
    barcode: "5000169068540",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "1ltr",
    fallbackName: "Lemonade",
    fallbackBrand: "Waitrose",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "lacnor-lacnor-lemonade",
    barcode: "6291016000038",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "200ml",
    fallbackName: "Lacnor Lemonade",
    fallbackBrand: "Lacnor",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "7-up-seven-up",
    barcode: "0001200001736",
    db: "off",
    category: "drink",
    subcategory: null,
    sizeLabel: "355ml",
    fallbackName: "Seven Up",
    fallbackBrand: "7 Up",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "kinder-kinder-joy",
    barcode: "80310891",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "20 g",
    fallbackName: "Kinder Joy",
    fallbackBrand: "Kinder",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "c-te-d-or-chocolat-au-lait",
    barcode: "5410081202555",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "47g",
    fallbackName: "Chocolat au lait",
    fallbackBrand: "Côte d'Or",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "millennium-dark-chocolate-quot-millennium-favorite-quot-brut",
    barcode: "4820005195848",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100 g",
    fallbackName: "Dark Chocolate \"Millennium Favorite\" Brut 80%",
    fallbackBrand: "Millennium",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "hershey-s-hershey-s-cocoa-409",
    barcode: "0034000052127",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "230g",
    fallbackName: "Hershey’s Cocoa في ١٠٠ غرام 409 سعرة حرارية",
    fallbackBrand: "Hershey's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mr-beast-feastables-peanut-butter",
    barcode: "0850027880280",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "2.1 oz",
    fallbackName: "FEASTABLES PEANUT BUTTER",
    fallbackBrand: "MR BEAST",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "choceur-milk-chocolate",
    barcode: "4068263007019",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100 g",
    fallbackName: "Milk Chocolate",
    fallbackBrand: "Choceur",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "canterel-dark-chocolate-with-sea-salt",
    barcode: "7640110709825",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100g",
    fallbackName: "Dark Chocolate with Sea Salt*",
    fallbackBrand: "Canterel",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "dulcinea-chocolate-negro-72-cacao",
    barcode: "8410510010215",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100 g",
    fallbackName: "Chocolate negro 72% cacao",
    fallbackBrand: "Dulcinea",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "well-naturally-milk-chocolate",
    barcode: "9311914800022",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "90 g",
    fallbackName: "Milk chocolate",
    fallbackBrand: "Well Naturally",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "aldi-bourbon-vanille",
    barcode: "4061458021609",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "125g",
    fallbackName: "Bourbon Vanille",
    fallbackBrand: "Aldi",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "chic-n-choc-dar-chocolate",
    barcode: "6299200051248",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100g",
    fallbackName: "Dar chocolate",
    fallbackBrand: "Chic n-choc",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "super-fudgio-chocolate-caramel-w-salt",
    barcode: "5903205740298",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "50 g",
    fallbackName: "Chocolate Caramel w/ Salt",
    fallbackBrand: "Super Fudgio",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "organic-larder-peanut-dark-chocolate",
    barcode: "6291108225936",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "53 g",
    fallbackName: "Peanut Dark Chocolate",
    fallbackBrand: "Organic Larder",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "chocodate-chocolate-date-almond-coconut",
    barcode: "6291011054302",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "250g",
    fallbackName: "Chocolate Date Almond Coconut",
    fallbackBrand: "Chocodate",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "keto-real-ketella-cream-dark",
    barcode: "6297001558584",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "90g",
    fallbackName: "Ketella Cream Dark",
    fallbackBrand: "Keto Real",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "chic-n-choc-white-chocolate",
    barcode: "6299200051255",
    db: "off",
    category: "snacks",
    subcategory: null,
    sizeLabel: "100g",
    fallbackName: "White Chocolate",
    fallbackBrand: "Chic n Choc",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "carrefour-epeautre-lentilles-petits-pois-soja",
    barcode: "3560070823840",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "400 g",
    fallbackName: "Epeautre & lentilles Petits pois & soja",
    fallbackBrand: "Carrefour",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "california-garden-california-garden-red-kidney-beans-ready-t",
    barcode: "0032894010278",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "400 g",
    fallbackName: "California garden red kidney beans ready to eat dark",
    fallbackBrand: "California Garden",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "marks-and-spencer-good-health-soup-mix",
    barcode: "5000169088036",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "500g",
    fallbackName: "Soup mix",
    fallbackBrand: "Marks and Spencer Good Health",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "auga-baked-beans",
    barcode: "4779039730351",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "400 g",
    fallbackName: "Baked Beans",
    fallbackBrand: "Auga",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "auga-chilli-beans",
    barcode: "4779039730382",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "400 g",
    fallbackName: "Chilli Beans",
    fallbackBrand: "Auga",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "brahmins-fried-rava",
    barcode: "8906014080057",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "1kg",
    fallbackName: "Fried Rava",
    fallbackBrand: "brahmins",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "trader-joe-s-smoked-sardines",
    barcode: "00265270",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "120 g",
    fallbackName: "Smoked sardines",
    fallbackBrand: "Trader Joe's",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "california-garden-tuna-slices",
    barcode: "0032894015419",
    db: "off",
    category: "food",
    subcategory: "canned_food",
    sizeLabel: "120g",
    fallbackName: "tuna slices",
    fallbackBrand: "California garden",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "santa-maria-tortilla-large",
    barcode: "7311311021169",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "371 g",
    fallbackName: "Tortilla Large",
    fallbackBrand: "Santa Maria",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "family-time-wraps-el-sabor",
    barcode: "5202175002192",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "8 pieces, 320g",
    fallbackName: "Wraps el sabor",
    fallbackBrand: "Family time",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "mountain-bread-pty-ltd-rye-wraps",
    barcode: "0789673000042",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "200 g",
    fallbackName: "Rye Wraps",
    fallbackBrand: "Mountain Bread Pty Ltd",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },
  {
    slug: "muchachos-tortilla-wraps-whole-wheat",
    barcode: "6299200055772",
    db: "off",
    category: "bread",
    subcategory: null,
    sizeLabel: "245 g",
    fallbackName: "TORTILLA WRAPS WHOLE WHEAT",
    fallbackBrand: "Muchachos",
    retailers: ["carrefour-uae", "spinneys", "noon", "amazon-ae"],
  },

];

export const RETAILERS = [
  {
    slug: "carrefour-uae",
    name: "Carrefour UAE",
    websiteUrl: "https://www.carrefouruae.com",
    connector: "hand",
  },
  { slug: "spinneys", name: "Spinneys", websiteUrl: "https://www.spinneys.com", connector: "hand" },
  { slug: "noon", name: "Noon", websiteUrl: "https://www.noon.com", connector: "hand" },
  { slug: "amazon-ae", name: "Amazon.ae", websiteUrl: "https://www.amazon.ae", connector: "hand" },
  { slug: "kibsons", name: "Kibsons", websiteUrl: "https://www.kibsons.com", connector: "hand" },
];
